<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Cancel</name>
   <tag></tag>
   <elementGuidId>fea97717-a166-41b8-ac30-cde7d52b72b1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='336b6c26eb5c4a25967a7a8847710f54']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#336b6c26eb5c4a25967a7a8847710f54</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Cancel&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>49afce4f-0ea4-45ff-bcb6-b556f91108ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>WBNN WFNN WG-O WBAO WOLN</value>
      <webElementGuid>15b78580-2fd6-46f2-b42f-ef399aa19aab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-automation-activebutton</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>bf261e27-c5f3-40a5-84d8-8fe590025229</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-automation-id</name>
      <type>Main</type>
      <value>wd-CommandButton_uic_cancelButton</value>
      <webElementGuid>040b676f-0ae4-43e1-82f6-46b95db94577</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>336b6c26eb5c4a25967a7a8847710f54</value>
      <webElementGuid>91fac4e2-b5c8-4975-8fa0-8c20addf7a07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-uxi-actionbutton-action</name>
      <type>Main</type>
      <value>bpf-cancel</value>
      <webElementGuid>544c7713-c9c0-4f2b-b42b-983ab240e5cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Cancel</value>
      <webElementGuid>5a4ce9d8-02b4-4c4c-92b9-05cf338f85e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-automation-button-type</name>
      <type>Main</type>
      <value>AUXILIARY_ALT</value>
      <webElementGuid>8d768f6b-7404-471a-820c-011269b8e3ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-automation-wizard-delimiter-visible</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>49578e4b-648d-4321-a699-b9d143e957c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>fd67a084-0928-4283-99b2-34031ce274ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Cancel</value>
      <webElementGuid>d40b38de-b581-4d00-8393-f46a2c6eb17f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;336b6c26eb5c4a25967a7a8847710f54&quot;)</value>
      <webElementGuid>fe45995c-5af6-48e6-902a-1df6029760ec</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='336b6c26eb5c4a25967a7a8847710f54']</value>
      <webElementGuid>59557a7a-39d3-45d6-b1a9-8511e6b9da79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Supervisory Organization'])[1]/following::button[5]</value>
      <webElementGuid>278547c8-fb8b-4407-b7d7-b4ad8f53ed0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Create Position'])[1]/following::button[6]</value>
      <webElementGuid>5603ac68-f505-4b8b-8d6d-fa93bb4c9dc8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='OK'])[1]/preceding::button[2]</value>
      <webElementGuid>d740aa93-7075-4733-ae1e-473a8034d403</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div[2]/div[2]/button</value>
      <webElementGuid>ab499f7c-3895-4080-822e-28baf8a31575</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = '336b6c26eb5c4a25967a7a8847710f54' and @title = 'Cancel' and @type = 'button' and (text() = 'Cancel' or . = 'Cancel')]</value>
      <webElementGuid>8aad1690-edba-430d-8444-28cc0090865e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
