<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Supervisory Organizations</name>
   <tag></tag>
   <elementGuidId>0630ac03-ff7b-401c-9bcd-5e9cda96f260</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='promptOption-55cdcfba-3e5f-43a5-b0a5-8faa0c5ec4f5']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#promptOption-55cdcfba-3e5f-43a5-b0a5-8faa0c5ec4f5</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Supervisory Organizations&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>723186ae-66cd-4241-9b1e-1ace6dbaca37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>promptOption-55cdcfba-3e5f-43a5-b0a5-8faa0c5ec4f5</value>
      <webElementGuid>ddb8a10f-a0bb-478a-b424-e74bf08254c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-automation-id</name>
      <type>Main</type>
      <value>promptOption</value>
      <webElementGuid>608be47e-67bc-45a5-a650-c748ccec4b2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-automation-label</name>
      <type>Main</type>
      <value>Supervisory Organizations</value>
      <webElementGuid>6af27599-8349-4955-855b-90d22c3d33af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-svf4lv-LabelContainer-1 edt0qdt4</value>
      <webElementGuid>cd0a87d8-faaa-47e5-939b-4565bf560ed5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Supervisory Organizations</value>
      <webElementGuid>908b39eb-da5d-458b-84f2-dd4b3a032c63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;promptOption-55cdcfba-3e5f-43a5-b0a5-8faa0c5ec4f5&quot;)</value>
      <webElementGuid>c48b10dd-f09e-466e-9af0-1b95f7eca669</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='promptOption-55cdcfba-3e5f-43a5-b0a5-8faa0c5ec4f5']</value>
      <webElementGuid>a2dd98d9-381f-477c-a96a-2823e504dc5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='menuItem-45$2764']/div/div</value>
      <webElementGuid>0c2f305d-aea8-4e29-955d-f12576beb9bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='OK'])[1]/following::div[11]</value>
      <webElementGuid>e4d1af27-be54-485b-b80b-27cf27de5988</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/following::div[12]</value>
      <webElementGuid>b670355a-8e3d-4cac-b48a-006963d1d9e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Active Supervisory Organizations by Hierarchy'])[1]/preceding::div[2]</value>
      <webElementGuid>b3b1b9df-d202-4d17-be0b-a859c37944b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Supervisory Organizations by Location'])[1]/preceding::div[6]</value>
      <webElementGuid>1b4bacd3-525f-46c4-a97f-9ec0cb455fe7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Supervisory Organizations']/parent::*</value>
      <webElementGuid>efa69d33-116f-49a0-a21d-fd27ccbec80c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[12]/div/div/div/div/div/div/div/div/div/div</value>
      <webElementGuid>aac6cc3c-5489-441a-b516-96b9815d1fc5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'promptOption-55cdcfba-3e5f-43a5-b0a5-8faa0c5ec4f5' and (text() = 'Supervisory Organizations' or . = 'Supervisory Organizations')]</value>
      <webElementGuid>18249e00-4bce-4720-bb20-e210b9852eb8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
