<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_100 AR Info</name>
   <tag></tag>
   <elementGuidId>d078fae3-35b1-47ec-8a2c-283736bb3140</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='promptOption-c6596eef-9da4-4e78-adb6-21e2fdfa36de']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#promptOption-c6596eef-9da4-4e78-adb6-21e2fdfa36de</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;100 AR Info&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>bf85e7e6-c208-465f-b6d0-2f70e7f8ba93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>promptOption-c6596eef-9da4-4e78-adb6-21e2fdfa36de</value>
      <webElementGuid>d809d2d0-0be2-4d03-be08-18aff53ca725</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-automation-id</name>
      <type>Main</type>
      <value>promptOption</value>
      <webElementGuid>645a6292-0eb5-4344-8f9b-255d6fe6518b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-automation-label</name>
      <type>Main</type>
      <value>100 AR Info</value>
      <webElementGuid>c559ba72-4ded-48ee-9775-4b5fd3c72d64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-83ob51-LabelContainer-1 edt0qdt4</value>
      <webElementGuid>37ab041a-feb0-464c-ac0c-4d86f859d7c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>100 AR Info</value>
      <webElementGuid>1dc82fa9-d4eb-4db9-b55a-e73e4d8ebefd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;promptOption-c6596eef-9da4-4e78-adb6-21e2fdfa36de&quot;)</value>
      <webElementGuid>bc37219a-053c-4da5-abe1-7483916eaf5b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='promptOption-c6596eef-9da4-4e78-adb6-21e2fdfa36de']</value>
      <webElementGuid>26118126-e193-4d48-b77b-88a3495c72ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='menuItem-2500$380']/div/div[2]</value>
      <webElementGuid>77a52684-4fc6-4ac6-b207-68522dc987f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='OK'])[1]/following::div[20]</value>
      <webElementGuid>acc27726-6e94-4b1c-8684-81550bba634c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/following::div[21]</value>
      <webElementGuid>19952a9b-3b5d-4983-be50-e8617018e10b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AA New Hires Department'])[1]/preceding::div[22]</value>
      <webElementGuid>f77cef93-cf86-4342-ad28-cffa71ccebdb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Accounting Operations'])[1]/preceding::div[34]</value>
      <webElementGuid>365db697-2710-4123-a975-b32fbddfd5aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='100 AR Info']/parent::*</value>
      <webElementGuid>e1ef2368-974b-4709-ab9e-14b7c3d210fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[12]/div/div/div[2]/div/div/div/div/div/div/div[2]</value>
      <webElementGuid>fa51da77-ce30-4380-821b-5193ed051425</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'promptOption-c6596eef-9da4-4e78-adb6-21e2fdfa36de' and (text() = '100 AR Info' or . = '100 AR Info')]</value>
      <webElementGuid>b62f0afa-e2bc-4f1a-9d79-b18b9ecb48a2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
