<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Create Position</name>
   <tag></tag>
   <elementGuidId>75d22f68-5713-47d4-90e0-8606552e08cc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;wd-searchInput&quot;]/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.WKXK</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Create Position&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>c370f4d8-c6c0-4687-bdfc-2f23c34bcca3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-automation-id</name>
      <type>Main</type>
      <value>pageHeaderTitleText</value>
      <webElementGuid>49e4d7f4-0caf-416d-8f50-50f8b477f387</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>WKXK</value>
      <webElementGuid>9ac8b895-294f-42ed-828c-375af0bb36b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Create Position</value>
      <webElementGuid>9c2d744f-faed-454e-88af-2230118f8431</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Create Position</value>
      <webElementGuid>2f58c29e-6f22-473b-b33e-1b89dfdb2abc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;heading_94109cd2-813f-4a14-b0ae-cd321d5f9910&quot;)/span[@class=&quot;WKXK&quot;]</value>
      <webElementGuid>08ad70f5-83de-40b6-8e61-8d24ef3dc275</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//h1[@id='heading_94109cd2-813f-4a14-b0ae-cd321d5f9910']/span</value>
      <webElementGuid>6b6546e8-6531-4f26-bb73-27bf091375f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign Out'])[1]/following::span[9]</value>
      <webElementGuid>b65b4401-4472-40df-bb70-b2a579b9196f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='opens new window'])[2]/following::span[11]</value>
      <webElementGuid>ef467e38-2b5b-46a7-bebe-a84d08456020</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Supervisory Organization'])[1]/preceding::span[2]</value>
      <webElementGuid>864097ed-4ced-47bd-91d2-a8e75bae1b44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Position Request Reason'])[1]/preceding::span[2]</value>
      <webElementGuid>1cffc5fe-5195-45a6-bf46-e9c928f107ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Create Position']/parent::*</value>
      <webElementGuid>6c40ecaf-b9e1-4b28-a4b2-e54449495bcd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h1/span</value>
      <webElementGuid>368f5f1d-91e7-46e5-a65b-151706c51053</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@title = 'Create Position' and (text() = 'Create Position' or . = 'Create Position')]</value>
      <webElementGuid>571d6bbd-f222-4aa8-8e9e-c4b984413082</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
