<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Ouvrir une session</name>
   <tag></tag>
   <elementGuidId>8bf9bf99-249c-4676-804e-0f6c0958032c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.GDPVGE1BBUC > button[type=&quot;button&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Ouvrir une session&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>10006c08-97a6-4415-b9ee-86b30e4da79c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>2f193d91-d306-476d-8f6f-cb902d570dbc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-automation-id</name>
      <type>Main</type>
      <value>goButton</value>
      <webElementGuid>43340e91-8635-4a2b-a97d-68cfe0fa0083</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Ouvrir une session</value>
      <webElementGuid>7a30e90b-d9e3-4399-b5e1-b238b8d3a0bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;container&quot;)/div[@class=&quot;GDPVGE1BNXB GDPVGE1BPXB GDPVGE1BF0B&quot;]/div[@class=&quot;GDPVGE1BOXB&quot;]/div[@class=&quot;GDPVGE1BOYB&quot;]/div[@class=&quot;GDPVGE1BI-B&quot;]/div[1]/div[1]/div[@class=&quot;GDPVGE1BAUC&quot;]/div[1]/div[@class=&quot;GDPVGE1BBUC&quot;]/button[1]</value>
      <webElementGuid>5fe62480-f66e-4cee-b19b-a642d3eefc54</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[3]</value>
      <webElementGuid>662403a8-344f-4634-b477-0e06492c829a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='container']/div/div/div[2]/div[2]/div/div/div/div/div[3]/button</value>
      <webElementGuid>7bec506a-6d0a-41f7-974d-ab0384f4ee6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mot de passe'])[1]/following::button[2]</value>
      <webElementGuid>13df969e-5d7f-4a9f-a135-9b0c17429dcb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Changer le mot de passe'])[1]/preceding::button[1]</value>
      <webElementGuid>71072f80-d723-4e25-a2a2-647f3b132ccd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Avis aux utilisateurs'])[1]/preceding::button[1]</value>
      <webElementGuid>d38e50d3-4198-4820-9e12-f2d4fba1070d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Ouvrir une session']/parent::*</value>
      <webElementGuid>87ce03f4-0be0-4fc9-af4c-7cde7f46b10a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/button</value>
      <webElementGuid>3b39df99-84d7-4abf-bc7b-f2be4aa35415</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Ouvrir une session' or . = 'Ouvrir une session')]</value>
      <webElementGuid>a2e1d46f-f0d5-4c56-8a64-04a325c36d6f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
