<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Mot de passe_gwt-PasswordTextBox GDPVGE1BC3B</name>
   <tag></tag>
   <elementGuidId>c1c8d13b-eb8d-4bbb-b0a6-5fb77d2f8c4b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@type='password']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.gwt-PasswordTextBox.GDPVGE1BC3B</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Mot de passe&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6de7c2bd-564a-40c0-a06a-26684aaa21f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>353ff1ae-43e1-4c3a-9efd-31b8258b2ff8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gwt-PasswordTextBox GDPVGE1BC3B</value>
      <webElementGuid>24ff88c2-2363-4c02-bd67-54719a041a60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocapitalize</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>f609d2e5-2d75-4975-8dab-30549423ffe1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocorrect</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>e412feda-feac-4cfe-b2af-720b1a12e838</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>2aec1b34-1f53-4ff3-8fec-6ea5bbd04569</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Mot de passe</value>
      <webElementGuid>510c2357-84b2-4f94-bd83-b7151bd1b7df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;container&quot;)/div[@class=&quot;GDPVGE1BNXB GDPVGE1BPXB GDPVGE1BF0B&quot;]/div[@class=&quot;GDPVGE1BOXB&quot;]/div[@class=&quot;GDPVGE1BOYB&quot;]/div[@class=&quot;GDPVGE1BI-B&quot;]/div[1]/div[1]/div[@class=&quot;GDPVGE1BAUC&quot;]/div[1]/div[@class=&quot;GDPVGE1BBUC&quot;]/div[2]/div[@class=&quot;GDPVGE1BP2B&quot;]/input[@class=&quot;gwt-PasswordTextBox GDPVGE1BC3B&quot;]</value>
      <webElementGuid>7c1b07de-608e-449f-9234-70b5193b81fd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@type='password']</value>
      <webElementGuid>f50e1ff5-bdf6-47cf-8245-a820bae01c44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='container']/div/div/div[2]/div[2]/div/div/div/div/div[3]/div[2]/div/input</value>
      <webElementGuid>da32f549-8a1f-4d8d-96c5-d56419b27d67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>f107ef87-16ca-4053-8ea2-2646d066cad7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password']</value>
      <webElementGuid>12f10345-77b8-4630-ae1c-6edefa46545a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
