<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Hire Employee</name>
   <tag></tag>
   <elementGuidId>f9e74e24-1dc3-40b1-b5db-aab9a07838c1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='wd-autocomplete-result-0']/div/div[2]/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.css-1c47t1k-HeaderTextContainer.e1d42mt04</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>div >> internal:has-text=/^Hire Employee$/</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>ccd5603d-03d2-4465-af09-8d243d6b13d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dir</name>
      <type>Main</type>
      <value>ltr</value>
      <webElementGuid>19209427-35e8-4614-ae10-e48ce6d7334f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-automation-id</name>
      <type>Main</type>
      <value>searchInputAutoCompleteResultFullText</value>
      <webElementGuid>a9db8097-9845-4ca4-9a99-645259957cf0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-1c47t1k-HeaderTextContainer e1d42mt04</value>
      <webElementGuid>b6d36095-3c26-4232-bf47-4891992b508c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Hire Employee</value>
      <webElementGuid>6dc7c854-a091-41ec-ac76-bb2441588c1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wd-autocomplete-result-0&quot;)/div[@class=&quot;css-1mmkhti-Container e1d42mt00&quot;]/div[@class=&quot;css-oi45gb-LabelContainer e1d42mt03&quot;]/div[@class=&quot;css-1c47t1k-HeaderTextContainer e1d42mt04&quot;]</value>
      <webElementGuid>2f99dc9b-2e3b-41f1-88a8-3e86d8411123</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='wd-autocomplete-result-0']/div/div[2]/div</value>
      <webElementGuid>6b32a58f-881d-49a1-983c-51f5565f2639</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dismiss'])[1]/following::div[11]</value>
      <webElementGuid>7f2d824d-aee2-4f61-9480-100c872a03d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/div/div[2]/div</value>
      <webElementGuid>cc63df5b-a8ea-47f7-88d6-d3c842abad33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Hire Employee' or . = 'Hire Employee')]</value>
      <webElementGuid>f405b909-2388-46fb-8c3d-2ad402dfcfca</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
