<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Create Pre-Hire</name>
   <tag></tag>
   <elementGuidId>3cb729ce-00e4-4537-942a-f9e9912d663e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='wd-recent-searches-result-0']/div/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.css-4owvqo-LabelContainer.e11j0byn1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#wd-recent-searches-result-0 >> internal:text=&quot;Create Pre-Hire&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>0f60fa12-e67b-44da-bb90-3fa5bef90b14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-automation-id</name>
      <type>Main</type>
      <value>searchInputRecentSearchItemLabel</value>
      <webElementGuid>27a72540-7c67-41fd-b7c7-36da2cabf54d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-4owvqo-LabelContainer e11j0byn1</value>
      <webElementGuid>29b322dc-e1cc-4343-8536-a3827323d5d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Create Pre-Hire</value>
      <webElementGuid>1140ac9d-64db-4ba0-99f4-3665804f6965</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wd-recent-searches-result-0&quot;)/div[@class=&quot;css-150a7ys-Container e11j0byn0&quot;]/span[@class=&quot;css-4owvqo-LabelContainer e11j0byn1&quot;]</value>
      <webElementGuid>0d472338-80b7-4d16-add2-56bff42326cb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='wd-recent-searches-result-0']/div/span</value>
      <webElementGuid>eb663a59-c105-4885-a0e4-5b8b227e0177</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Clear'])[1]/following::span[2]</value>
      <webElementGuid>5ddd8505-ac90-4534-9abc-4571880e00be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Recent Searches'])[1]/following::span[2]</value>
      <webElementGuid>26c017a7-e952-436a-b13c-b2fed7e13571</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Create Pre-Hire'])[2]/preceding::span[2]</value>
      <webElementGuid>c17ef904-7950-47cb-a53b-3ed22d523cb4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hire Employee'])[1]/preceding::span[4]</value>
      <webElementGuid>52deab06-b28f-4748-a77d-c0664b030880</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Create Pre-Hire']/parent::*</value>
      <webElementGuid>64f3ff00-de41-4e4f-9af6-bbc10f252bea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/div/span</value>
      <webElementGuid>bebf1ea7-42b5-4726-87ab-bd507ed472bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Create Pre-Hire' or . = 'Create Pre-Hire')]</value>
      <webElementGuid>04a2f660-3718-404a-8c93-5dea251c4dfa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
