<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Landline</name>
   <tag></tag>
   <elementGuidId>b8192543-f5cf-4e35-9d62-6310291e9bd7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='promptOption-gwt-uid-5']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#promptOption-gwt-uid-5</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Landline&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>70d5498b-0aaa-4532-a980-f79cbc58f07e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gwt-Label WKIP WDHP</value>
      <webElementGuid>03103dbc-71bd-4286-9406-ed3346961142</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-automation-id</name>
      <type>Main</type>
      <value>promptOption</value>
      <webElementGuid>cef4ab9d-0e96-4586-b888-5aa5fe66b05b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>promptOption-gwt-uid-5</value>
      <webElementGuid>f4f43c35-1bc0-42a2-b51b-acc3148ac78a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-automation-label</name>
      <type>Main</type>
      <value>Landline</value>
      <webElementGuid>d33b7178-9484-41b7-b3fc-f0da0c60fd11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Landline</value>
      <webElementGuid>c7115859-7a82-43c8-94da-83d3ddaa75eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Landline</value>
      <webElementGuid>da0fda86-cddb-43c5-8b3f-7cc96d492428</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Landline</value>
      <webElementGuid>a4c899b8-557e-4c26-843f-9b5a2d8be671</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;promptOption-gwt-uid-5&quot;)</value>
      <webElementGuid>1bf08236-78f2-4fc5-b32e-c8a5b881f4d6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='promptOption-gwt-uid-5']</value>
      <webElementGuid>d4322e78-2644-472d-972b-9efdfc0e393c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='56$31774-input-entry-1']/div/div/div</value>
      <webElementGuid>68758ae2-0b4b-4b86-a044-f46212e33e9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='select one'])[1]/following::div[4]</value>
      <webElementGuid>ba435aed-057a-49ad-b018-c9ec6a3cf32b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/following::div[13]</value>
      <webElementGuid>18f626a4-8d62-4355-b8a1-7bba6c73e19a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mobile'])[2]/preceding::div[1]</value>
      <webElementGuid>fbae93df-39cc-4d8d-9fbd-9c7d00eecc6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Landline']/parent::*</value>
      <webElementGuid>d88b504d-1545-4a0f-8a86-d432092c783b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[12]/div/ul/li[2]/div/div/div/div</value>
      <webElementGuid>7f6930b6-c0bd-4cca-889e-48177fd60943</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'promptOption-gwt-uid-5' and @title = 'Landline' and (text() = 'Landline' or . = 'Landline')]</value>
      <webElementGuid>853b8e0e-747a-47b6-81ed-021c7f608909</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
