<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Prefix_56551055--uid21-input</name>
   <tag></tag>
   <elementGuidId>4aec3df0-8959-4970-a623-fade805e951c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='56$551055--uid21-input']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Prefix&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8fa910d6-db6b-42c8-aea1-47e73a0d47f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dir</name>
      <type>Main</type>
      <value>ltr</value>
      <webElementGuid>1f3d29d0-ee34-4958-8d9a-1945715c137b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search</value>
      <webElementGuid>0b3a83b3-3f15-42b8-824d-8351ca069b9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>280</value>
      <webElementGuid>0ac01bff-8c68-4824-b9bf-81a27aeccf43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>5d51e02d-153f-49d2-b3bd-83f0b0d0956c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>622d4c33-5127-43dc-a337-c9975b9d3d50</value>
      <webElementGuid>339c38c9-037c-4cfa-b52d-55359181145e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>56$551055--uid21-formLabel</value>
      <webElementGuid>e6f21d64-4592-4411-9a8b-ce5cf1f8673a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>d1262b8f-7d2f-4fc4-95b1-70769047f8e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>a8e4fe70-2f03-4332-9c17-2a11c8f9495e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>c0fac1ea-849c-454b-b76d-e7d847b72171</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>54e26f25-c998-48c6-b243-f23f33119b94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-uxi-element-id</name>
      <type>Main</type>
      <value>selectinput-56$551055</value>
      <webElementGuid>221a8ab3-fec6-4b91-9c17-5b86f46022ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-uxi-widget-type</name>
      <type>Main</type>
      <value>selectinput</value>
      <webElementGuid>d8cc6d65-c735-4d6e-a29d-28215d44e860</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-uxi-multiselect-id</name>
      <type>Main</type>
      <value>56$551055--uid21</value>
      <webElementGuid>16fa0384-09c1-4e35-82b1-ff4e546168e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>56$551055--uid21-input</value>
      <webElementGuid>3b34843b-d60f-4208-8c03-e84f4848281d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-5ow9ag-InputContainer edt0qdt22</value>
      <webElementGuid>f4ea09f3-af1a-430f-b562-6a6890acac9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-automation-id</name>
      <type>Main</type>
      <value>searchBox</value>
      <webElementGuid>8c0abbd2-28b5-4b51-9908-e2166d380621</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;56$551055--uid21-input&quot;)</value>
      <webElementGuid>0527f7d5-bc5a-4968-861e-e57a06eed54e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='56$551055--uid21-input']</value>
      <webElementGuid>6c22556a-5e9d-43a2-81d7-4f226f5df568</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='9305d263-6d5d-4350-9d27-e4a7528948d0']/div/div/input</value>
      <webElementGuid>384fc17c-dbc6-4246-b31d-3c4cdd9a6825</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div[2]/div/div/ul/li/div[2]/div/div/div/div/div/div/input</value>
      <webElementGuid>e69e0599-11c1-464b-a10b-093e10f0de5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Search' and @id = '56$551055--uid21-input']</value>
      <webElementGuid>e8a50b86-3702-48dc-a8e4-fee2fe3fe843</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
