<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Search_1</name>
   <tag></tag>
   <elementGuidId>e50f251b-21b6-41bd-8e53-182207f61a0a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='5a95b4194565415eb4a2419c00bc1401']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#5a95b4194565415eb4a2419c00bc1401</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Search Search&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>4bcbc359-f862-4f84-bea1-03f4d617c49d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>WEON WION WJ0O WEBO WCNN</value>
      <webElementGuid>73b80fa9-43cd-46fd-8ab7-6e9d2b805dac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-automation-activebutton</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>7cedefa1-999a-44bb-822b-57825042decc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-automation-id</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>25f8d53f-0551-4206-87df-6cfd543d704e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>5a95b4194565415eb4a2419c00bc1401</value>
      <webElementGuid>d6875325-74b8-4182-854e-183d42f83f11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Search</value>
      <webElementGuid>7c38dd7f-0e20-49db-b07b-22b733a7a396</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-automation-button-type</name>
      <type>Main</type>
      <value>AUXILIARY</value>
      <webElementGuid>cf35217a-fe41-484a-a27d-945ac2991c66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-automation-task-ids</name>
      <type>Main</type>
      <value>PARTIAL_372_3495$157</value>
      <webElementGuid>c0ca7359-00e4-46d6-8339-b638561c59b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Search Search</value>
      <webElementGuid>c74a1669-026c-496d-99f2-87b93a1bac2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>010711c1-8450-479a-aaf1-1898bde0366c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Search</value>
      <webElementGuid>b81cbf42-b5b9-4790-abb6-53cd0184bb30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;5a95b4194565415eb4a2419c00bc1401&quot;)</value>
      <webElementGuid>f9902804-fc6e-4cb3-a884-6d978c2cc1fe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='5a95b4194565415eb4a2419c00bc1401']</value>
      <webElementGuid>1c120bbe-0b5a-4c64-9ace-84bd61745be6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wd-DropDownCommandButton-NO_METADATA_ID-uid105']/button</value>
      <webElementGuid>d4ffe8ad-a85c-4d4e-8799-347ff6475ef7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ID Type'])[1]/following::button[1]</value>
      <webElementGuid>b0fc64c3-d85d-491d-8066-12dec4b00126</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Phone Number'])[1]/following::button[1]</value>
      <webElementGuid>4d0d90ce-91d2-4882-b9b0-795449aae45c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='More (0)'])[1]/preceding::button[2]</value>
      <webElementGuid>ade45878-4aae-47e8-9ca9-35a69bc7451e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/ul/li/div/button</value>
      <webElementGuid>00c08ea7-6737-44cd-a5ff-e7956b3c9a27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = '5a95b4194565415eb4a2419c00bc1401' and @title = 'Search' and @type = 'button' and (text() = 'Search' or . = 'Search')]</value>
      <webElementGuid>4f5aa463-d10b-455c-84ff-3db46673d047</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
