<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Search</name>
   <tag></tag>
   <elementGuidId>d3598477-2774-4e17-9f86-fae99bbf110e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='4e6ea1730d9f4f15a694e3a7f74f4c1a']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#4e6ea1730d9f4f15a694e3a7f74f4c1a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Search Search&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>5403e4ef-37e5-4a50-866f-12bfdb079ffb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>WEON WION WJ0O WEBO WCNN</value>
      <webElementGuid>d81d1de4-968b-4e4f-acb9-c6674d006ad2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-automation-activebutton</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>01a2000e-eb7a-4fbe-9dc3-ff8d5bd1b019</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-automation-id</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>1f3dc599-8d87-48bc-afb5-d5a2dcbc606c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>4e6ea1730d9f4f15a694e3a7f74f4c1a</value>
      <webElementGuid>80820977-e7ce-4b39-baba-e4210a5e2c7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Search</value>
      <webElementGuid>4c999a08-e4dd-4fd8-b4d7-2f2c6efddf0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-automation-button-type</name>
      <type>Main</type>
      <value>AUXILIARY</value>
      <webElementGuid>f0680cbe-532f-42f8-bd63-684589c93cf0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-automation-task-ids</name>
      <type>Main</type>
      <value>PARTIAL_372_3495$157</value>
      <webElementGuid>bafb9a08-661f-48b5-8e8b-2329f4b527c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Search Search</value>
      <webElementGuid>c4d5279f-629b-4b7e-8d37-be520cb2e15a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>bfcd2bbe-b1da-4229-95c8-d8c032eb44bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Search</value>
      <webElementGuid>423e5628-58b4-408e-ba7f-fffb4fc30eec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;4e6ea1730d9f4f15a694e3a7f74f4c1a&quot;)</value>
      <webElementGuid>c25530b6-f1f8-4f2e-90ca-f760c97e4e8d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='4e6ea1730d9f4f15a694e3a7f74f4c1a']</value>
      <webElementGuid>a2188cc9-ed5c-47a7-a836-0d46920f5ba4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wd-DropDownCommandButton-NO_METADATA_ID-uid18']/button</value>
      <webElementGuid>7df38789-ad76-40e5-b296-9c77f90a13b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ID Type'])[1]/following::button[1]</value>
      <webElementGuid>fe21a5c9-25ac-4eb7-92fa-1cb617682bc2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Phone Number'])[1]/following::button[1]</value>
      <webElementGuid>b96f1e2b-0a4f-47fa-a410-8d074d7538d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='More (0)'])[1]/preceding::button[2]</value>
      <webElementGuid>e0596862-bb73-4836-b2f0-9fe2f17cf111</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/ul/li/div/button</value>
      <webElementGuid>72b7ec85-bc58-4cd5-a673-0578901190e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = '4e6ea1730d9f4f15a694e3a7f74f4c1a' and @title = 'Search' and @type = 'button' and (text() = 'Search' or . = 'Search')]</value>
      <webElementGuid>ca440888-25ce-4fc2-83b8-f49fc1f848ed</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
