<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_0 Search Results</name>
   <tag></tag>
   <elementGuidId>998878bd-9809-4a18-a1a2-ed38031510a3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='wd-FieldSet-1599$24774-uid66-label']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;0 Search Results&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>e80ad6b8-43bd-414f-85f8-eac4e15485e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>WGYO</value>
      <webElementGuid>7ff72f69-31ef-41ac-acd4-4cc0f2cd348b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-automation-id</name>
      <type>Main</type>
      <value>fieldSetLegendLabel</value>
      <webElementGuid>4498c60e-a419-466d-bbdb-1f5e769117ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f0f8fc8f-7725-43c1-9d52-227943b390e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>wd-FieldSet-1599$24774-uid66-label</value>
      <webElementGuid>2a98367a-9a7e-41e7-ba95-357659acbaad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>0 Search Results</value>
      <webElementGuid>dc37e7a1-6b16-461e-b4f6-be8944d8617d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>0 Search Results</value>
      <webElementGuid>cd5f1f0c-0d2d-46f1-b964-59be5bc27569</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>0 Search Results</value>
      <webElementGuid>b58dfd7c-482a-48c6-838f-5217c7220bb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wd-FieldSet-1599$24774-uid66-label&quot;)</value>
      <webElementGuid>e4fe4396-c526-4385-85c0-05264f80fced</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='wd-FieldSet-1599$24774-uid66-label']</value>
      <webElementGuid>7105ea11-1291-4936-b39f-df0e811cdcd5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//h3[@id='heading_94e93563-fc14-404e-9065-8e62f8a7aaa7']/span</value>
      <webElementGuid>de580f10-cb5b-4a54-aa22-83993f0d0fc8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='More (0)'])[1]/following::span[2]</value>
      <webElementGuid>ebf9b31a-e1ad-485d-91e0-9181ef0b48ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search'])[1]/following::span[5]</value>
      <webElementGuid>759b1c22-a69e-4535-8963-d72e56a659a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='More (0)'])[2]/preceding::span[1]</value>
      <webElementGuid>35214db4-bbfb-47ba-9016-187cc367cbc8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Start Hire'])[1]/preceding::span[3]</value>
      <webElementGuid>02d4d1ba-71d8-4eba-bcc1-398eb11db7fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='0 Search Results']/parent::*</value>
      <webElementGuid>10b0a131-21e4-4189-8f82-496975c8c52a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/div/div/h3/span</value>
      <webElementGuid>363aba0b-144f-4eea-baed-601d03092fcb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'wd-FieldSet-1599$24774-uid66-label' and @title = '0 Search Results' and (text() = '0 Search Results' or . = '0 Search Results')]</value>
      <webElementGuid>32a01275-a36b-4118-ac63-5268f72341e0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
