<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_OK</name>
   <tag></tag>
   <elementGuidId>8dd3192c-7a4f-4431-b787-49600dddae3d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#b5b50cb7ce034f0b9cb21eda517c33ee</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='b5b50cb7ce034f0b9cb21eda517c33ee']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;OK&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>50c7b40f-f1b6-4575-b276-df7ed07bc485</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>WEON WION WJ0O WEBO WLPN</value>
      <webElementGuid>6a61b186-4ae9-47d4-a444-53670986d602</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-automation-activebutton</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>44041326-a19a-4406-a30e-88323359f9fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-automation-id</name>
      <type>Main</type>
      <value>wd-CommandButton_uic_okButton</value>
      <webElementGuid>a749bbc4-b03e-42bb-a8f8-209a72db3b53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b5b50cb7ce034f0b9cb21eda517c33ee</value>
      <webElementGuid>718afe27-ddff-4549-94ae-a2b8441e7f23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-uxi-actionbutton-action</name>
      <type>Main</type>
      <value>bpf-submit</value>
      <webElementGuid>eca2dfa4-fe3b-44c2-a327-1a53af86d746</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>OK</value>
      <webElementGuid>33222a77-75fc-4887-a91d-6c7ceb3cc8c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-automation-button-type</name>
      <type>Main</type>
      <value>SECONDARY</value>
      <webElementGuid>c44bdb05-d457-4f13-afcc-6d6306c46049</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-automation-wizard-delimiter-visible</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>431ee37f-4121-4642-8b3f-90be66045c53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>6b205fc4-2756-4c2c-a358-a6042b4fc06f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>OK</value>
      <webElementGuid>08c3cdf2-b072-4005-875a-ef33b0bd98a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b5b50cb7ce034f0b9cb21eda517c33ee&quot;)</value>
      <webElementGuid>7edd75aa-28cf-444f-a6ef-a3889a962d76</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='b5b50cb7ce034f0b9cb21eda517c33ee']</value>
      <webElementGuid>22b8329e-6297-4696-86ef-db6cb96f0018</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mainContent']/section/div[2]/div/div/button</value>
      <webElementGuid>6d9b9c4b-2593-4e60-ac56-487a89def01d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Act As'])[1]/following::button[1]</value>
      <webElementGuid>4d664714-bc76-42f4-934d-76a8769dc1ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Start Proxy'])[1]/following::button[1]</value>
      <webElementGuid>31d9673c-bdea-4da4-8c47-a96a48698e98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/preceding::button[2]</value>
      <webElementGuid>7ecf2e65-7926-4ee7-81b4-94a9e63c7083</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/button</value>
      <webElementGuid>8f7557bd-362f-47f1-b547-22d808f66d16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'b5b50cb7ce034f0b9cb21eda517c33ee' and @title = 'OK' and @type = 'button' and (text() = 'OK' or . = 'OK')]</value>
      <webElementGuid>51fb0105-a8d5-4147-a9f6-3454bef51eae</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
