<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Act As_56279654--uid5-input</name>
   <tag></tag>
   <elementGuidId>e41037f7-6802-42ed-837a-44bca7b3c010</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='56$279654--uid5-input']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@placeholder = 'Search' and @id = '56$279654--uid5-input']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Act As&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b14aef79-7222-44b8-aa15-85ad9b90b14f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dir</name>
      <type>Main</type>
      <value>ltr</value>
      <webElementGuid>1fad3ccf-4be5-4163-b2df-45d110ab0c58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search</value>
      <webElementGuid>b8ddc2d1-f940-4fb9-94db-52e088900d6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>280</value>
      <webElementGuid>9053afd3-1fd7-4b90-ace1-c45ee8c84312</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>390d95d5-9946-41cf-9ada-acf14b7b6dd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>42df96ee-daa7-4fca-9508-1016b770b8df</value>
      <webElementGuid>1be61812-b2ad-41c5-ab22-f6177f3f6452</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>56$279654--uid5-formLabel</value>
      <webElementGuid>9fa5d710-95ca-41b4-a07a-4ca2af293541</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>e451f665-99fe-41ee-8ca2-b8296191beea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>c78613c8-7e28-4cd7-81fd-edc3267e420b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>2a51ac73-3b3f-4ad4-a015-11e19229b30b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>e5f0a1f3-7645-4552-a78f-de3bdbaf8dbc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-uxi-element-id</name>
      <type>Main</type>
      <value>selectinput-56$279654</value>
      <webElementGuid>89e8fe21-355e-4b31-bb73-da4c33b505d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-uxi-widget-type</name>
      <type>Main</type>
      <value>selectinput</value>
      <webElementGuid>76fe28a9-64a6-4ffa-a182-37294f3560c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-uxi-multiselect-id</name>
      <type>Main</type>
      <value>56$279654--uid5</value>
      <webElementGuid>8b464801-7c8e-425f-8b24-8350b8779cd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>56$279654--uid5-input</value>
      <webElementGuid>4a476828-6a4e-40f9-bce1-670ca7e7cbcd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-5ow9ag-InputContainer edt0qdt22</value>
      <webElementGuid>0a189a75-1a15-4e8a-9c8e-c119f92e8cab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-automation-id</name>
      <type>Main</type>
      <value>searchBox</value>
      <webElementGuid>53447cfd-db1d-476f-b136-96d7f80564d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;56$279654--uid5-input&quot;)</value>
      <webElementGuid>5bb063b3-0e50-4613-8ce4-6d1133a3b255</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='56$279654--uid5-input']</value>
      <webElementGuid>e113dd30-9acd-406a-90ba-e70ddded7084</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='c4ca7e1d-3cc3-4ec7-b86c-a14ea5ee25a8']/div/div/input</value>
      <webElementGuid>b525009a-6c98-4afd-9a16-50cf8da88304</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/div[2]/div/div/div/div/div/div/input</value>
      <webElementGuid>87f44824-9aec-4bbe-8b9c-dc178faa2c39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Search' and @id = '56$279654--uid5-input']</value>
      <webElementGuid>da7e4716-4d81-43b0-bffb-9c249dbab3d8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
