<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Act As_56279654--uid5-input</name>
   <tag></tag>
   <elementGuidId>e41037f7-6802-42ed-837a-44bca7b3c010</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@placeholder = 'Search' and @id = '56$279654--uid5-input']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;56$279654--uid5-input&quot;]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Act As&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1beffce2-404c-4645-80d6-51402ca228f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dir</name>
      <type>Main</type>
      <value>ltr</value>
      <webElementGuid>521c4a89-06bf-4d2c-b6ab-b70c75a7e641</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search</value>
      <webElementGuid>a4caca60-0fde-4408-b2ce-2b454de337da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>280</value>
      <webElementGuid>4d4b75b5-c260-437f-a485-15b837c88857</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>be517faf-ab18-47fb-9b4f-bd1106af7e86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>69691c5d-1b2e-480a-a046-c32594d8de73</value>
      <webElementGuid>88a5506d-0c7e-4e57-9fb4-340524695a79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>56$279654--uid5-formLabel</value>
      <webElementGuid>a9d2f517-9bff-4135-af50-fe08ebe5e1ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>da00d4f8-682e-4187-b575-79563f1c036f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>d489789b-d0ed-4c73-b3aa-aef046de4827</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>4043f1ee-6ecf-4c25-b0b6-bb7daa10aff5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>44ced343-34bc-4f4e-8619-dabf7bb5e36b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-uxi-element-id</name>
      <type>Main</type>
      <value>selectinput-56$279654</value>
      <webElementGuid>6c1bf5a2-37b4-49bd-bec4-10b4841120b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-uxi-widget-type</name>
      <type>Main</type>
      <value>selectinput</value>
      <webElementGuid>6365663c-7da2-4cf6-8223-f6fead293205</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-uxi-multiselect-id</name>
      <type>Main</type>
      <value>56$279654--uid5</value>
      <webElementGuid>a2aa8d96-b92a-4d7c-941f-52a6e1969d7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>56$279654--uid5-input</value>
      <webElementGuid>9e034afa-c664-447c-b0bc-82310b809130</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-5ow9ag-InputContainer edt0qdt22</value>
      <webElementGuid>e8ba152e-c73d-41c3-9bab-c1c32d8dfc34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-automation-id</name>
      <type>Main</type>
      <value>searchBox</value>
      <webElementGuid>6d120887-f2f0-482b-b35a-1f0267b54a29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;56$279654--uid5-input&quot;)</value>
      <webElementGuid>8fab9237-dd02-4a3e-8158-88688234270f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='56$279654--uid5-input']</value>
      <webElementGuid>0a4ed7d5-af39-4d07-ac20-ac24cd456754</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='9a5a8c6b-b922-4798-a5f3-5841619d858a']/div/div/input</value>
      <webElementGuid>90705c41-0b75-4691-bf11-7fc4d8eb81fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/div[2]/div/div/div/div/div/div/input</value>
      <webElementGuid>0554bc4b-81ed-40ce-a503-055a2201883b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Search' and @id = '56$279654--uid5-input']</value>
      <webElementGuid>f7d58506-1648-45fc-966f-c7ada603b4ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='c4ca7e1d-3cc3-4ec7-b86c-a14ea5ee25a8']/div/div/input</value>
      <webElementGuid>2e69eb75-b384-451f-9359-08873b4028b9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
