<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Create Pre-Hire</name>
   <tag></tag>
   <elementGuidId>c233bc0e-c4dd-430d-9d12-9d2c8219608d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='b7af6588ef6b479eb2347e74e6a996f9']/div/div/div/div/div/ol/li/div/ol/li/div/div/div/h3/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.pexsearch-12ncsxh-link</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Create Pre-Hire&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>91ea3a21-3cc6-46ba-a66a-f876423f1625</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/deloittecansrv_dpt1/d/task/2997$155.htmld</value>
      <webElementGuid>51d4f1d1-e6bb-44d8-a7c6-e5940e28898f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-uxi-rank</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>6f9bd6b2-329b-411b-ac1c-39b297eb7545</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-uxi-instance-id</name>
      <type>Main</type>
      <value>2997$155</value>
      <webElementGuid>78e64d58-da35-4796-970d-86e34406e370</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-automation-id</name>
      <type>Main</type>
      <value>pex-search-results-header-title-link</value>
      <webElementGuid>32ef445a-147c-45b1-bdc5-80db6f48c21b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-uxi-element-id</name>
      <type>Main</type>
      <value>pex-search-results-header-title-link</value>
      <webElementGuid>f616cd4d-6835-411d-9ad2-494fff9d7918</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pexsearch-12ncsxh-link</value>
      <webElementGuid>8933f675-6e35-4814-adbe-14db94959a27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Create Pre-Hire</value>
      <webElementGuid>45db0003-27e7-4f53-87c0-f7e07d60b363</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b7af6588ef6b479eb2347e74e6a996f9&quot;)/div[@class=&quot;css-s76t0&quot;]/div[@class=&quot;pexsearch-y5mloq-searchPageContainer&quot;]/div[@class=&quot;pexsearch-qxrhiz-middleColumnScroll&quot;]/div[@class=&quot;pexsearch-btit7y-middleColumn&quot;]/div[1]/ol[@class=&quot;pexsearch-1jcdqns&quot;]/li[@class=&quot;pexsearch-i0cxx-category_withSeparator&quot;]/div[1]/ol[@class=&quot;pexsearch-wt0qt3-list&quot;]/li[@class=&quot;pexsearch-1txnm9c-listItem&quot;]/div[@class=&quot;pexsearch-z1ad66-resultRow&quot;]/div[@class=&quot;pexsearch-2xznwz-resultContainer&quot;]/div[@class=&quot;pexsearch-5y57s1-notLastSpacing&quot;]/h3[@class=&quot;pexsearch-9dlyth-linkHeading&quot;]/a[@class=&quot;pexsearch-12ncsxh-link&quot;]</value>
      <webElementGuid>3693f348-42e1-4cd5-aba8-867ff86b9537</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b7af6588ef6b479eb2347e74e6a996f9']/div/div/div/div/div/ol/li/div/ol/li/div/div/div/h3/a</value>
      <webElementGuid>a88ce5db-5865-4108-b2c6-81c4970b2f3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Create Pre-Hire')]</value>
      <webElementGuid>a3beab4d-d65c-4d9f-b539-2ad45dd42df5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tasks and Reports'])[2]/following::a[1]</value>
      <webElementGuid>e1868ef9-c38f-4138-afd3-db4192a7274a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search Results'])[1]/following::a[1]</value>
      <webElementGuid>bb2cc51a-0315-4e46-915a-93ef99acbe32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Create Expense Report for Pre-Hire'])[1]/preceding::a[1]</value>
      <webElementGuid>1c41583b-d5d6-4bdf-bff4-3aafe82790f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Create Pre-Hire']/parent::*</value>
      <webElementGuid>eef31153-1cc1-4823-b732-ce2fea844c12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/deloittecansrv_dpt1/d/task/2997$155.htmld')]</value>
      <webElementGuid>d326bc62-f8bc-48d4-8cdb-0eec0ca8b8fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h3/a</value>
      <webElementGuid>0d27b4ff-c148-47cd-b9e9-8b4f3db35fb9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/deloittecansrv_dpt1/d/task/2997$155.htmld' and (text() = 'Create Pre-Hire' or . = 'Create Pre-Hire')]</value>
      <webElementGuid>ffdf4a3d-1222-4b8b-b419-4934cb22bd8a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
