<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Start Proxy</name>
   <tag></tag>
   <elementGuidId>4d5d56ab-c8eb-44dd-bce3-d9edd321d613</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='d5bdebed089b46ab814cf25830097a29']/div/div/div/div/div/ol/li/div/ol/li/div/div/div/h3/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.pexsearch-12ncsxh-link</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Start Proxy&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>54df525f-fa26-49d5-ac1c-2310112a009c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/deloittecansrv_dpt1/d/task/2997$6729.htmld</value>
      <webElementGuid>fc7b5f4b-34bf-42eb-a427-c4a56db08bfe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-uxi-rank</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>fa8569bd-42e0-4f8a-a00e-9121f0a0a509</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-uxi-instance-id</name>
      <type>Main</type>
      <value>2997$6729</value>
      <webElementGuid>0b09408e-37e2-4522-9402-9fb6d44b5bfe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-automation-id</name>
      <type>Main</type>
      <value>pex-search-results-header-title-link</value>
      <webElementGuid>7964954d-a743-4bc5-b932-b291fb80e9c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-uxi-element-id</name>
      <type>Main</type>
      <value>pex-search-results-header-title-link</value>
      <webElementGuid>983723a2-ef52-4baa-8a20-aa816d900219</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pexsearch-12ncsxh-link</value>
      <webElementGuid>e560b5a1-d5a1-4aa5-ab62-87eea2e74f56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Start Proxy</value>
      <webElementGuid>e452e15e-7f19-4d29-bb9a-126623026051</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;d5bdebed089b46ab814cf25830097a29&quot;)/div[@class=&quot;css-s76t0&quot;]/div[@class=&quot;pexsearch-y5mloq-searchPageContainer&quot;]/div[@class=&quot;pexsearch-qxrhiz-middleColumnScroll&quot;]/div[@class=&quot;pexsearch-btit7y-middleColumn&quot;]/div[1]/ol[@class=&quot;pexsearch-17mrx6g&quot;]/li[@class=&quot;pexsearch-fg9owr-category_withSeparator&quot;]/div[1]/ol[@class=&quot;pexsearch-wt0qt3-list&quot;]/li[@class=&quot;pexsearch-1txnm9c-listItem&quot;]/div[@class=&quot;pexsearch-gmyk2o-resultRow&quot;]/div[@class=&quot;pexsearch-2xznwz-resultContainer&quot;]/div[@class=&quot;pexsearch-5y57s1-notLastSpacing&quot;]/h3[@class=&quot;pexsearch-9dlyth-linkHeading&quot;]/a[@class=&quot;pexsearch-12ncsxh-link&quot;]</value>
      <webElementGuid>992d56ec-1290-4e44-970f-1419bed44919</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='d5bdebed089b46ab814cf25830097a29']/div/div/div/div/div/ol/li/div/ol/li/div/div/div/h3/a</value>
      <webElementGuid>25e3d486-f393-42d1-a537-7c5e6cfa066a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Start Proxy')]</value>
      <webElementGuid>ee461f57-a836-4297-83cf-d8af970992b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tasks and Reports'])[2]/following::a[1]</value>
      <webElementGuid>e55abddf-28b6-4326-9b4c-c7bbaad80c76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search Results'])[1]/following::a[1]</value>
      <webElementGuid>cfd4dfe1-2c99-4993-96d9-c7af5ad3cf92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Try searching under More Categories.'])[1]/preceding::a[1]</value>
      <webElementGuid>1293c86c-25fd-41ec-b024-88ad51c8ce54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Start Proxy']/parent::*</value>
      <webElementGuid>c0581d16-c8ba-4987-8abf-f094385c49c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/deloittecansrv_dpt1/d/task/2997$6729.htmld')]</value>
      <webElementGuid>6650e797-8daa-4b64-b2d5-e847bd16baca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h3/a</value>
      <webElementGuid>fce80570-8b66-42ec-a142-3300c205e890</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/deloittecansrv_dpt1/d/task/2997$6729.htmld' and (text() = 'Start Proxy' or . = 'Start Proxy')]</value>
      <webElementGuid>b6a62422-0859-465b-bfd6-4170e2899598</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
