<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Start Proxy</name>
   <tag></tag>
   <elementGuidId>7bc455fb-b642-4cc0-9ba7-8afa7e41d0f7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='wd-autocomplete-result-0']/div/div[2]/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.css-1c47t1k-HeaderTextContainer.e1d42mt04</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;suggested results&quot;i >> div >> internal:has-text=/^Start Proxy$/</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>29708ec8-1838-456c-a922-a6670df78813</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dir</name>
      <type>Main</type>
      <value>ltr</value>
      <webElementGuid>c30a4052-baee-413c-a203-7d753bfc48af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-automation-id</name>
      <type>Main</type>
      <value>searchInputAutoCompleteResultFullText</value>
      <webElementGuid>ed13c570-495b-419b-b3a6-2fd80e1f1d2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-1c47t1k-HeaderTextContainer e1d42mt04</value>
      <webElementGuid>56260d57-7b00-4cb0-a664-af1595dc9d02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Start Proxy</value>
      <webElementGuid>ffe8e78c-ede8-4f15-a3ad-7782611536d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wd-autocomplete-result-0&quot;)/div[@class=&quot;css-1mmkhti-Container e1d42mt00&quot;]/div[@class=&quot;css-oi45gb-LabelContainer e1d42mt03&quot;]/div[@class=&quot;css-1c47t1k-HeaderTextContainer e1d42mt04&quot;]</value>
      <webElementGuid>3c01c423-2507-4c03-a46e-d76002f3f255</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='wd-autocomplete-result-0']/div/div[2]/div</value>
      <webElementGuid>60a54637-e595-462a-b7fb-76eb8010194a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add Shortcuts'])[1]/following::div[15]</value>
      <webElementGuid>8bdff70c-56a5-4a02-b433-378f4c28cff7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Use Shortcuts to save reports, tasks, and external links here.'])[1]/following::div[16]</value>
      <webElementGuid>75b2a25c-f853-42bf-96eb-ac085b5e23a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/div/div[2]/div</value>
      <webElementGuid>90a23ff8-b82e-4956-b11c-9b80f3fe7e3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Start Proxy' or . = 'Start Proxy')]</value>
      <webElementGuid>8e6237f3-0ff0-4c0b-8b25-d16734b8ace7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
