<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_MENU</name>
   <tag></tag>
   <elementGuidId>a1f1a6b2-7632-4ae1-88b6-767187a6ec03</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app-chrome-container']/div/div[6]/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.wdappchrome-i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>div >> internal:has-text=/^MENU$/ >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>46da28b4-a258-4b56-be41-28141318f6df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>wdappchrome-i</value>
      <webElementGuid>519ef03b-a93a-484b-bd37-8297e926376d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>MENU</value>
      <webElementGuid>0551b055-4e30-4eec-a8aa-0e706cc99a6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app-chrome-container&quot;)/div[@class=&quot;wdappchrome-a&quot;]/div[@class=&quot;wdappchrome-g&quot;]/div[@class=&quot;wdappchrome-i&quot;]</value>
      <webElementGuid>7e37bfb6-a16d-42f5-9593-d63ada059c3b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app-chrome-container']/div/div[6]/div</value>
      <webElementGuid>2d2c03b3-698e-4808-a07a-cc42cb00d833</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Accessibility Overview'])[1]/following::div[6]</value>
      <webElementGuid>71360639-3d77-4007-be8a-c183f5a13163</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Notifications Items'])[1]/preceding::div[18]</value>
      <webElementGuid>de712bd4-da3b-4a70-8afa-3b8fc80b660d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[6]/div</value>
      <webElementGuid>c4eec6f2-c6b8-4bd0-b05f-d2f7a7082ed3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'MENU' or . = 'MENU')]</value>
      <webElementGuid>df29f531-5f2d-488d-bffe-8fba465aab38</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
